### ISSUE TITLE
signed taco not accepted/verified by Tableau - Error Code: 14D18B1F

### ISSUE THREAD

**Issue by clach04** [ActianCorp/actian_tableau_connector#1]
Signed taco https://github.com/ActianCorp/actian_tableau_connector/releases/tag/signed_test verifies with JDK but fails Tableau check:

    Unexpected Error
    There was a problem while running the connector plugin. Reinstall the plugin or contact the plugin provider.
    Note that you might need to make local configuration changes to resolve the error.
    Error Code: 14D18B1F
    Package signature verification failed during connection creation.

Logged https://github.com/tableau/connector-plugin-sdk/issues/401 to progress.

**Comment by clach04** [comment]
Confirmed Tableau Desktop bug. Closing, for now document workaround(s).

**Comment by estebgonza** [comment]
I have the same error, but my package seems correctly signed.
What is your workaround? 
Did you just disable signing verification with -DDisableVerifyConnectorPluginSignature=true ?

**Comment by clach04** [comment]
@estebgonza correct. I've not seen a patch for this yet. I'm keeping an eye on https://github.com/tableau/connector-plugin-sdk/issues/401 (when I see 20.1 out I'll try that too).
