### ISSUE TITLE
[Tableau Feedback] Show SSL Check Box

### ISSUE THREAD

**Issue by jainam1995** [ActianCorp/actian_tableau_connector#7]
Have you tried adding the following line of code [SSL Check Box](https://github.com/tableau/connector-plugin-sdk/blob/master/samples/plugins/postgres_odbc/connection-dialog.tcd#L10) for the ssl check box to show up ?

**Comment by clach04** [comment]
@jainam1995 we have not experimented with that dialog option - I don't think we're likely to make use of it if I understand what it does.

Our drivers have encryption support that doesn't go over an SSL port (443). Whilst encryption can be specified client side, if the server requires encryption the client will auto enable (or the connection will be rejected).

I'll leave this issue open for feedback for a week in case I've misunderstood and we need to revisit that dialog option.

**Comment by jainam1995** [comment]
Got it . Was not aware of the encryption feature and wanted to make aware of the ssl checkbox feature tableau  provides in case that was required.
