### ISSUE TITLE
[Tableau Feedback] Un-uniformity in attributes in dialect file

### ISSUE THREAD

**Issue by jainam1995** [ActianCorp/actian_tableau_connector#9]
Certain lines of code in the dialect file have a mix of Capital and Small letters . For example  : https://github.com/ActianCorp/actian_tableau_connector/blob/master/actian_odbc/dialect.tdd#L486

`(yEaR(%3)`

This occurs in some other lines of code as well. Just wanted to ask if this was expected or by mistake

**Comment by clach04** [comment]
Good catch @jainam1995.

I'm convinced this is accidental - as the functions in Actian Avalanche are case insensitive this isn't significant to functionality but it would be nice to be consistent.
